### ISSUE TITLE
TOD 2022 Roadmap:1.0

### ISSUE THREAD

**Issue by todhamma** [palasangha/Treasures-Of-Dhamma#35]
1. Data Sorting
- [ ] Raw
- [ ] Processing (Project files. Eg: Premier Pro, After Effects, Photoshop, Audition files)
- [ ] Final 
- [ ] Variations (Versions for Social media, Mega Events, etc.)

**Comment by todhamma** [comment]
- Checked tasks are ready, unchecked are in progress or planned. Classified with priority.
- Please feel free to add an issue, comment, request more info, or ask for clarification.

### 1. Data Sorting with Standard Naming procedure
- [ ] Raw
- [ ] Processing (Project files. Eg: Premiere Pro, After Effects, Photoshop, Audition files)
- [ ] Final 
- [ ] Variations (Versions for Social media, Mega Events, etc.)
