### ISSUE TITLE
As a developer, I want to explore and investigate Text modal, and provide a forward looking recommendation

### ISSUE THREAD

**Issue by Vijay-train** [palasangha/Treasures-Of-Dhamma#67]
Investigate and evaluate Text Annotation options and provide a recommendation.

- [ ] Clear recommendation on Text Annotation approach
- [ ] POC demonstrating the chosen Text Annotation

Create a sample POC with GPT4 for Text Generation Model

- [ ] A full e2e automated POC that will take some sample text data set, fine tuned, with validation set and deployed. The POC should be able to generate summaries, create FAQ  and answer questions
